### ISSUE TITLE
PowerWalker STL

### ISSUE THREAD

**Issue by TriKriSta** [thomasjsn/powerwalker-python-lib#1]
can this library work with PowerWalker Basic VI STL ?

**Comment by thomasjsn** [comment]
No, this library is only for the ATS and PDU. But that UPS has HID USB connection, which works with nut: https://networkupstools.org/docs/man/usbhid-ups.html

This is how I configure my PowerWalker UPS with nut:
```ini
maxretry = 3
retrydelay = 5
pollinterval = 5
synchronous = yes

[ups]
        driver = usbhid-ups
        port = auto
        vendorid = 06da
```

**Comment by TriKriSta** [comment]
Thanks!

**Comment by thomasjsn** [comment]
No problem :)
